api:
  # cachet url
  url: https://demo.cachethq.io/api/v1
  # cachet api token
  token: 9yMHsdioQosnyVK4iCVR
  insecure: false
# https://golang.org/src/time/format.go#L57
date_format: 02/01/2006 15:04:05 MST
monitors:
  # http monitor example
  - name: google
    # test url
    target: https://google.com
    # strict certificate checking for https
    strict: true
    # HTTP method
    method: POST
    
    # set to update component (either component_id or metric_id/metrics are required)
    component_id: 1
    
    # set to post to cachet metrics [ response_time_metric_id, availability_metric_id, incident_count_metric_id ] or metric_id: response_time_metric_id  (graph)
    metrics:
        response_time: [ 4, 5 ]

    # custom templates (see readme for details)
    template:
      investigating:
        subject: "{{ .Monitor.Name }} - {{ .SystemName }}"
        message: "{{ .Monitor.Name }} check **failed** (server time: {{ .now }})\n\n{{ .FailReason }}"
      fixed:
        subject: "I HAVE BEEN FIXED"

    # launch script depending on event (failed or successful check)
    shellhook:    
      on_success: /fullpath/shellhook_onsuccess.sh
      on_failure: /fullpath/shellhook_onfailure.sh

    # webhook to be called when a partial occurs
    webhook:
      on_partial:
        url: "http://www.site.com/webhook"
        content_type: "text/plain"
        investigating:        
          message: "{{ .Monitor.Name }} check **failed** (server time: {{ .now }})\n\n{{ .FailReason }}"
      on_critical:
        url: "http://www.site.com/webhook"
        content_type: "text/plain"
        investigating:        
          message: "{{ .Monitor.Name }} check **failed** (server time: {{ .now }})\n\n{{ .FailReason }}"
    
    # seconds between checks
    interval: 1
    # seconds for timeout
    timeout: 1

    # resync component data every x check
    resync: 60

    # necessary ticks before saturation (before evaluating the downtime)
    history_size: 10

    # if % or (count: threshold_count) of downtime is over this threshold, open an incident
    threshold: 50

    # or if % or (count: threshold_critical_count/threshold_partial_count) of downtime is over partical/critical open an incident with the related incident level
    threshold_critical: 80
    threshold_partial: 20

    # custom HTTP headers
    headers:
      Authorization: Basic <hash>
    # expected status code (either status code or body must be supplied)
    expected_status_code: 200
    # regex to match body
    expected_body: "P.*NG"

  # mock monitor example
  - name: mock
    
    # set to update component (either component_id or metric_id are required)
    component_id: 3

    # seconds between checks
    interval: 1

    type: mock

    shellhook:
        on_success: /fullpath/shellhook_onsuccess.sh
        on_fail: /fullpath/shellhook_onfail.sh

  # dns monitor example
  - name: dns
    # fqdn
    target: matej.me.
    # question type (A/AAAA/CNAME/...)
    question: mx
    type: dns
    # set component_id/metric_id
    component_id: 2
    # poll every 1s
    interval: 1
    timeout: 1
    # custom DNS server (defaults to system)
    dns: 8.8.4.4:53
    answers:
      - exact: 10 aspmx2.googlemail.com.
      - exact: 1 aspmx.l.google.com.
      - exact: 10 aspmx3.googlemail.com.